name: EBAC 22

on:
  push:
    branches: [ gitactions ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Start server and run tests
        uses: start-server-and-test@v2.0.10
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          test: npm run test
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
